version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
    ports:
      - '8080:80'

  backend:
    build:
      context: ./back-end
    ports:
      - '8000:8000'
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/vue-db?authSource=admin
      MONGO_DBNAME: vue-db
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
